import = ["/home/teenarp2026/.cache/wal/colors-alacritty.toml"]
live_config_reload = true

#[class]
#general = "Alacritty"
#instance = "Alacritty"

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "Victor Mono"
style = "Semibold Italic"

[font.bold_italic]
family = "Victor Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Victor Mono"
style = "Italic"

[font.normal]
family = "Victor Mono"
style = "SemiBold Italic"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

#[mouse.double_click]
#threshold = 300

#[mouse.triple_click]
#threshold = 300

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
program = "/usr/bin/fish"

#[visual_bell]
#animation = "EaseOutExpo"
#color = "#e4c9af"
#duration = 0.5

[window]
opacity = 0.5

[window.padding]
x = 10
y = 10
