[Setting]
spotify_path           = /opt/spotify/
prefs_path             = /home/teenarp2026/.config/spotify/prefs
color_scheme           = Vaporwave
replace_colors         = 1
overwrite_assets       = 1
spotify_launch_flags   = 
check_spicetify_update = 1
always_enable_devtools = 0
current_theme          = Comfy
inject_theme_js        = 1
inject_css             = 1

[Preprocesses]
remove_rtl_rule    = 1
expose_apis        = 1
disable_sentry     = 1
disable_ui_logging = 1

[AdditionalOptions]
extensions            = 
custom_apps           = marketplace
sidebar_config        = 0
home_config           = 1
experimental_features = 1

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.2.79.425.g1d0fcf61
with    = 2.43.2
