#! /bin/sh
numlockx
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6
bspc config border_width         2
bspc config window_gap           10
# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

#bspc rule -a glava state=floating layer=below sticky=true locked=true border=off
bspc rule -a kdeconnect.app state=floating
bspc rule -a Blueberry.py state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Google-chrome desktop='^2' -l monocle
bspc rule -a Chromium desktop='^2' -l monocle
bspc rule -a firefox desktop='^2'
bspc rule -a Spotify desktop='^3' state=floating
bspc rule -a GitKraken desktop='^6'
bspc rule -a Code desktop='^5'
bspc rule -a Screenkey manage=off
bspc rule -a env LD_PRELOAD=/usr/lib/spotify-adblock.so spotify %U desktop='^4'
killall lxpolkit dunst clipmenud kdeconnectd 
xsetroot -cursor_name left_ptr &
# Lxpolkit polkit gui
lxpolkit & 
# Dunst notification manager
dunst &
clipmenud &
# polybar and other stuff
$HOME/.config/polybar/launch.sh & 
#glava ! cant stop anymore..
glava-colors &
#glava -d -m radial &
wmname LG3D &
#chown teenarp2003 /sys/class/backlight/amdgpu_bl0/brightness
# sudo chgrp video  /sys/class/backlight/amdgpu_bl0/brightness
kdeconnectd &
