preload = /home/teenarp2026/.config/wallpaper/night_city.jpg
wallpaper = eDP-1,/home/teenarp2026/.config/wallpaper/night_city.jpg
wallpaper = DP-1,/home/teenarp2026/.config/wallpaper/night_city.jpg
wallpaper = DP-2,/home/teenarp2026/.config/wallpaper/night_city.jpg
wallpaper = DP-3,/home/teenarp2026/.config/wallpaper/night_city.jpg
wallpaper = DP-4,/home/teenarp2026/.config/wallpaper/night_city.jpg
splash = false
