wallpaper {
    monitor = eDP-1
    path = /home/teenarp2026/.config/wallpaper/854164.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/teenarp2026/.config/wallpaper/854164.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = /home/teenarp2026/.config/wallpaper/854164.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-4
    path = /home/teenarp2026/.config/wallpaper/854164.jpg
    fit_mode = cover
}

splash = false
