preload = /home/teenarp2026/.config/wallpaper/city-rain.png
wallpaper = eDP-1,/home/teenarp2026/.config/wallpaper/city-rain.png
wallpaper = DP-2,/home/teenarp2026/.config/wallpaper/city-rain.png
wallpaper = DP-3,/home/teenarp2026/.config/wallpaper/city-rain.png
wallpaper = DP-4,/home/teenarp2026/.config/wallpaper/city-rain.png
splash = false
