wallpaper {{
    monitor = eDP-1
    path = {wallpaper}
    fit_mode = fill
}}

wallpaper {{
    monitor = DP-2
    path = {wallpaper}
    fit_mode = fill
}}

wallpaper {{
    monitor = DP-3
    path = {wallpaper}
    fit_mode = fill
}}

wallpaper {{
    monitor = DP-4
    path = {wallpaper}
    fit_mode = fill
}}

splash = false
