#!/bin/bash

# Rofi wallpaper selection script
wallpaper=$(exa ~/.config/wallpaper | while read A ; do  echo -en "$A\x00icon\x1f~/.config/wallpaper/$A\n" ; done | rofi -dmenu -theme .config/rofi/wallpaper.rasi)

wallpapersel=$wallpaper
wallpaper_path=~/.config/wallpaper/$wallpapersel
# Set the theme using pywal
if [ -z "$wallpapersel" ]; then 
  wallpaper_path="NULL"; 
fi
wal -i "$wallpaper_path"
. "${HOME}/.cache/wal/colors.sh"
# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
glava-colors
betterlockscreen -u $wallpaper_path blur
if pgrep -x spotify >/dev/null 
  then
    spicetify apply
    sleep 4s
    picom-trans -n "Spotify" --opacity=65
  else
    echo "No Running Instance of Spotify"
fi
